/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 15.0
      io_method: "mmap"
      frame_id: "camera"
      pixel_format: "yuyv"
      image_width: 640
      image_height: 480
      camera_name: "picam360_front"
      camera_info_url: "package://usb_cam/config/camera_info.yaml"
